package action

import "github.com/ghf-go/goapp/base"

func IosIconAction() {
	src := base.GetArg(1)
	base.ImgReset(src, "icon-20.png", 20)
	base.ImgReset(src, "icon-20@2x.png", 40)
	base.ImgReset(src, "icon-20@3x.png", 60)
	base.ImgReset(src, "icon-24@2x.png", 48)
	base.ImgReset(src, "icon-27.5@2x.png", 55)
	base.ImgReset(src, "icon-29.png", 29)
	base.ImgReset(src, "icon-29@2x.png", 58)
	base.ImgReset(src, "icon-29@3x.png", 87)
	base.ImgReset(src, "icon-40.png", 40)
	base.ImgReset(src, "icon-40@2x.png", 80)
	base.ImgReset(src, "icon-44@2x.png", 88)
	base.ImgReset(src, "icon-50.png", 50)
	base.ImgReset(src, "icon-50@2x.png", 100)
	base.ImgReset(src, "icon-60@2x.png", 120)
	base.ImgReset(src, "icon-60@3x.png", 180)
	base.ImgReset(src, "icon-72.png", 72)
	base.ImgReset(src, "icon-72@2x.png", 144)
	base.ImgReset(src, "icon-76.png", 76)
	base.ImgReset(src, "icon-76@2x.png", 152)
	base.ImgReset(src, "icon-83.5@2x.png", 167)
	base.ImgReset(src, "icon-86@2x.png", 172)
	base.ImgReset(src, "icon-98@2x.png", 196)
	base.ImgReset(src, "icon-1024.png", 1024)
	base.ImgReset(src, "icon.png", 57)
	base.ImgReset(src, "icon@2x.png", 114)
}

func CordovaIosIconAction() {
	src := base.GetArg(1)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-20.png", 20)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-20@2x.png", 40)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-20@3x.png", 60)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-24@2x.png", 48)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-27.5@2x.png", 55)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-29.png", 29)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-29@2x.png", 58)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-29@3x.png", 87)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-40.png", 40)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-40@2x.png", 80)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-44@2x.png", 88)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-50.png", 50)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-50@2x.png", 100)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-60@2x.png", 120)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-60@3x.png", 180)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-72.png", 72)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-72@2x.png", 144)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-76.png", 76)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-76@2x.png", 152)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-83.5@2x.png", 167)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-86@2x.png", 172)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-98@2x.png", 196)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon-1024.png", 1024)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon.png", 57)
	base.ImgReset(src, "platforms/ios/myApp/Assets.xcassets/AppIcon.appiconset/icon@2x.png", 114)
}
